version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
    environment:
      CIRCLE_WORKFLOW_ID: workflow

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  new_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Hello to Sillians World in San Francisco > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - new_job:
          requires:
            - print_output_file